### ISSUE TITLE
About Generality of LPCAM. 

### ISSUE THREAD

**Issue by callmelaoyi** [zhaozhengChen/LPCAM#1]
I really appreciate your work on WSSS.
Now, I have some questions about LPCAM. I would like to know how LPCAM integrates with MCTformer, as reported in your experiment. Could you provide a detailed code or instruction description?

**Comment by zhaozhengChen** [comment]
Hi, thanks for your interest in our work, and my apologies for the delayed response.
In regards to the generation of PatchCAM in MCTformer-V2, it's quite similar to the classic CAM process. With this in mind, we've modified the MCTformer by simply replacing the PatchCAM with our proposed LPCAM.

**Comment by Italy2006** [comment]
> Hi, thanks for your interest in our work, and my apologies for the delayed response. In regards to the generation of PatchCAM in MCTformer-V2, it's quite similar to the classic CAM process. With this in mind, we've modified the MCTformer by simply replacing the PatchCAM with our proposed LPCAM.

Have you ever changed the hyperparameters inside? Like crf in Affinitynet?
