### ISSUE TITLE
K-Means does not converge for background features

### ISSUE THREAD

**Issue by lucasdavid** [zhaozhengChen/LPCAM#5]
Hello. Firstly, thank you for the great work.

I'm trying to reproduce the results and apply it to my own CAMs, but I'm somewhat stuck during K-Means. **Could you please share your features/cams, used as input to LPCAM?**

From what I gather, the K-Means over foreground features seem to converge as expected, while running it over background features frequently result in arbitrarily large `tol`'s. **Did you experience this as well? Can this be mitigated by some of the hyperparameters?**

My only differences to the original code are: 
1. I increased `selected_thres = 0.3`. Seemed like the sensible thing to do, considering my CAMs have a higher optimal thes.
3. I increased `tol` from 0.5 to 30 to accelerate training
4. I added a `max_iteration=100` parameter in kmeans_pytorch lib in order to prevent infinite loops

Here are training times for a few classes (plane, bike, bird, boat, bottle), for reference:

```shell
class id:  0 , class name: aeroplane
features selected    : torch.Size([14363, 2048]) torch.float32
features not selected: torch.Size([47038, 2048]) torch.float32
running k-means on cuda:0..
[running kmeans]: 10it [00:05,  1.89it/s, center_shift=22.108383, iteration=10, tol=30.000000]  
running k-means on cuda:0..
[running kmeans]: 101it [02:30,  1.45s/it, center_shift=18806.734375, iteration=101, tol=30.000000]Interrupted (iteration=101 > max_iteration=100)
[running kmeans]: 101it [02:30,  1.49s/it, center_shift=18806.734375, iteration=101, tol=30.000000]

class id:  1 , class name: bicycle
features selected    : torch.Size([9652, 2048]) torch.float32
features not selected: torch.Size([38520, 2048]) torch.float32
running k-means on cuda:0..
[running kmeans]: 13it [00:04,  3.11it/s, center_shift=21.436689, iteration=13, tol=30.000000]  
running k-means on cuda:0..
[running kmeans]: 101it [01:59,  1.18s/it, center_shift=15778.094727, iteration=101, tol=30.000000]Interrupted (iteration=101 > max_iteration=100)
[running kmeans]: 101it [01:59,  1.18s/it, center_shift=15778.094727, iteration=101, tol=30.000000]

class id:  2 , class name: bird
features selected    : torch.Size([14301, 2048]) torch.float32
features not selected: torch.Size([63019, 2048]) torch.float32
running k-means on cuda:0..
[running kmeans]: 13it [00:05,  2.22it/s, center_shift=29.299744, iteration=13, tol=30.000000]  
running k-means on cuda:0..
[running kmeans]: 101it [03:32,  1.93s/it, center_shift=36542.941406, iteration=101, tol=30.000000]Interrupted (iteration=101 > max_iteration=100)
[running kmeans]: 101it [03:32,  2.10s/it, center_shift=36542.941406, iteration=101, tol=30.000000]

class id:  3 , class name: boat
features selected    : torch.Size([12694, 2048]) torch.float32
features not selected: torch.Size([44381, 2048]) torch.float32
running k-means on cuda:0..
[running kmeans]: 17it [00:06,  2.43it/s, center_shift=29.191572, iteration=17, tol=30.000000]  
running k-means on cuda:0..
[running kmeans]: 101it [02:14,  1.33s/it, center_shift=51663.605469, iteration=101, tol=30.000000]Interrupted (iteration=101 > max_iteration=100)
[running kmeans]: 101it [02:14,  1.34s/it, center_shift=51663.605469, iteration=101, tol=30.000000]

class id:  4 , class name: bottle
features selected    : torch.Size([7840, 2048]) torch.float32
features not selected: torch.Size([57216, 2048]) torch.float32
running k-means on cuda:0..
[running kmeans]: 19it [00:05,  3.78it/s, center_shift=22.918352, iteration=19, tol=30.000000]  
running k-means on cuda:0..
[running kmeans]: 99it [02:50,  1.73s/it, center_shift=15.979640, iteration=99, tol=30.000000]    

[...]
```

**Comment by zhaozhengChen** [comment]
Hi, thanks for your interest in our work.
1. The features/cams used as input to LPCAM. You may run our code to get the features and cam. The ```save_feature``` function in ```make_lpcam.py``` will save features to files. The ```make_cam.py``` file will save cams to files. You may refer to the readme on how to run the code.
2. K-means on the background features do not converge. I haven't experienced that case. The only hyperparameter I used to control the convergence speed is ```tol```. It seems sometimes it can converge but sometimes it cannot in your provided log. Does the ```center_shift``` decrease as the iteration increases? Have you tried to change the number of clusters?

**Comment by lucasdavid** [comment]
Indeed, the problem was that most features were clustered in two or three clusters. I didn't try to reduce the number of centers, but I managed to make it work by computing the global mean and standard deviation from the features and normalizing them with it:
```py
u1, s1 = feature_selected.mean(), feature_selected.std()
u2, s2 = feature_not_selected.mean(), feature_not_selected.std()

feature_selected -= u1
feature_selected /= s1.clamp_(min=1e-5)
feature_not_selected -= u2
feature_not_selected /= s2.clamp_(min=1e-5)

cluster_ids_x, cluster_centers = kmeans(X=feature_selected, num_clusters=num_cluster, distance='cosine', device=torch.device('cuda:0'), tol=tol, max_iteration=101)
cluster_ids_x2, cluster_centers2 = kmeans(X=feature_not_selected, num_clusters=num_cluster, distance='cosine', device=torch.device('cuda:0'), tol=tol, max_iteration=101)
    
cluster_centers *= s1
cluster_centers += u1
cluster_centers2 *= s2
cluster_centers2 += u2
```

**Did you use the same hyperparameters (select_thres=0.1, class_t=0.9, context_t=0.9) when improving CAMs from AMN and MCTformer?** Unfortunately, I'm not getting a better result with LP-CAM than my baseline. :-(

```shell
| Baseline                      | t: 0.3 | miou: 0.631 |
| LP-CAM t=0.3 cls=0.9 ctx=0.9) | t: 0.3 | miou: 0.582 |
```

**Comment by zhaozhengChen** [comment]
For the select_thres, it is related to the threshold used in AMN (or MCTformer).
For the class_t and context_t, our LPCAM is not sensitive to them, so we use the same values.

**Comment by lucasdavid** [comment]
I see. Thank you for the info.
