### ISSUE TITLE
Is this applicable for binary classification problems?

### ISSUE THREAD

**Issue by fengxfeng0** [zhaozhengChen/LPCAM#7]
Hello! Thank you very much for your work. 
I'd like to know if it's also applicable for binary classification problems (with only one target class and the rest as background), where `num_classes` is set to 1? I'm currently trying this work, but I'm encountering issues during clustering.

**Comment by zhaozhengChen** [comment]
It should work, but I haven't ever tried binary classification. The num_classes should be set to 2.

**Comment by fengxfeng0** [comment]
Thank you for your reply.I will try!
